### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [WhenGryphonsFly/decomp-permuter#2]
Step: import.py file.c file.o function_name
file.c contains the nonmatching function and file.o contains the original assembled assembly
i'm using windows and devkitpro

**Comment by WhenGryphonsFly** [comment]
Can you take a screenshot of the exact command and output? I don't think import.py should be calling anything (that would be permute.py's job), so it would be nice to see what other output there is (if any). You can take a screenshot of just part of the screen with Win+Shift+S.

(Also, just to make sure, you're replacing function_name with the name of the actual function, correct? I don't see how that would cause this error, but I have similar things cause seemingly unrelated errors before.)

**Comment by H-A-M-G-E-R** [comment]
the .c file has one function and the file has the same name as the function

**Comment by H-A-M-G-E-R** [comment]
```
./../decomp-permuter-agbcc/import.py ./expected_objs/BoxFallingDebrisFalling.c ./expected_objs/BoxFallingDebrisFalling.o BoxFallingDebrisFalling
Compiler type: gcc
Function name: BoxFallingDebrisFalling
Compiler: /c/GitHub/agbcc/agbcc.exe -O2 -mthumb-interwork -fhex-asm -o /dev/stdout '|' /c/devkitPro/devkitARM/bin/arm-none-eabi-as.exe -mcpu=arm7tdmi {input} -o {output}
Assembler: /c/devkitPro/devkitARM/bin/arm-none-eabi-as.exe -mcpu=arm7tdmi {input} -o {output}
Preserving no macros. Use --preserve-macros='<regex>' to override.

Deleting directory nonmatchings/BoxFallingDebrisFalling (run with --keep to preserve it).
Traceback (most recent call last):
  File "C:\GitHub\decomp-permuter-agbcc\import.py", line 927, in <module>
    main(sys.argv[1:])
  File "C:\GitHub\decomp-permuter-agbcc\import.py", line 916, in main
    compile_base(compile_script, compilable_source, base_c_file, base_o_file)
  File "C:\GitHub\decomp-permuter-agbcc\import.py", line 757, in compile_base
    o_file = compiler.compile(source)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\decomp-permuter-agbcc\src\compiler.py", line 43, in compile
    subprocess.check_call(
  File "C:\Users\H A M\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H A M\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H A M\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\H A M\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application
```

**Comment by WhenGryphonsFly** [comment]
It's failing on the test compile, not the import itself. I'm not 100% confident that it's an upstream problem, but it's certainly leaning that way...

List of things to try, in order:

1. Navigate to C:\GitHub\agbcc\agbcc.exe, and make sure it is marked executable.
2. Try running the import script from the decomp-permuter-agbcc directory instead of the game directory.
3. Try running the import script, but append `--keep` to the end. Find the nonmatchings directory (should be in the folder where you run the script from), zip it, and then upload it here.

**Comment by H-A-M-G-E-R** [comment]
idk how to mark agbcc as executable
i compiled it myself from this fork for the zero mission decomp: https://github.com/YohannDR/mzm

**Comment by WhenGryphonsFly** [comment]
I don't have a Windows computer, so I don't know either. I suspect it's somewhere in file properties. I wouldn't worry about it, though. Just go straight to number 2, and if we need to go back later and check so be it.

**Comment by H-A-M-G-E-R** [comment]
i'm runnung in powershell

**Comment by WhenGryphonsFly** [comment]
Okay, thank you, that does answer a question I was about to ask.

You should be able to use `cd` in powershell to navigate to decomp-permuter-agbcc and run the import script from there. That is, number 2 is asking you to run `./import.py ../path_to_project/expected_objs/BoxFallingDebrisFalling.c ../path_to_project/expected_objs/BoxFallingDebrisFalling.o BoxFallingDebrisFalling`, where the `..` are in the paths to the files instead of the path to the import script.

**Comment by H-A-M-G-E-R** [comment]
`./import.py ../mf/expected_objs/BoxFallingDebrisFalling.c ../mf/expected_objs/BoxFallingDebrisFalling.o BoxFallingDebrisFalling`
still gives the same error

**Comment by WhenGryphonsFly** [comment]
Just checking to make sure you aren't having any problems with number 3. You should be able to just use the same command as in number 2 and just add `--keep` to the end. If you need a utility to zip a folder, I personally used 7-Zip back when I was on Windows - but Windows may come with a zip utility nowadays, I don't know.

**Comment by H-A-M-G-E-R** [comment]
Even with --keep, it still gives the same error, but the file is created.
[BoxFallingDebrisFalling.zip](https://github.com/user-attachments/files/17426332/BoxFallingDebrisFalling.zip)

**Comment by H-A-M-G-E-R** [comment]
and my permuter_settings.toml looks like this:
```
compiler_type = "gcc"
compiler_command = "/c/GitHub/agbcc/agbcc.exe -O2 -mthumb-interwork -fhex-asm -o /dev/stdout | /c/devkitPro/devkitARM/bin/arm-none-eabi-as.exe -mcpu=arm7tdmi"
assembler_command = "/c/devkitPro/devkitARM/bin/arm-none-eabi-as.exe -mcpu=arm7tdmi"

```

**Comment by WhenGryphonsFly** [comment]
Can you try running `./permute.py ./nonmatchings/BoxFallingDebrisFalling` from WSL? I'm wondering if this is a Powershell vs WSL issue.

**Comment by H-A-M-G-E-R** [comment]
I don't have WSL, but runnung MSYS2 on devkitpro:
```
"/c/Users/H A M/AppData/Local/Programs/Python/Python312/python.exe" ./permute.py ../mf/nonmatchings/BoxFallingDebrisFalling
C:\Users\H A M\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\GitHub\\decomp-permuter-agbcc\\permute.py': [Errno 2] No such file or directory
```
EDIT: it was just a typo
instead, runnung
```
"/c/Users/H A M/AppData/Local/Programs/Python/Python312/python.exe" ./permuter.py ../mf/nonmatchings/BoxFallingDebrisFalling
Loading...
../mf/nonmatchings/BoxFallingDebrisFalling\compile.sh must be marked executable.
```

**Comment by WhenGryphonsFly** [comment]
Okay, that gives me some ideas. Can you delete the nonmatchings folder, and then run the import script (without `--keep`) from MSYS2?

**Comment by H-A-M-G-E-R** [comment]
still the same error

**Comment by WhenGryphonsFly** [comment]
Very very odd. Okay, run the import script with `--keep` from MSYS2, and then try running the permute script again.

**Comment by H-A-M-G-E-R** [comment]
with --keep, literally gives the same error, but the files are created

**Comment by WhenGryphonsFly** [comment]
It's really hard to explain what I'm using the `--keep` flag for, but suffice to say that "same error, but the files are created" is the expected and intended result. Can you run the permute script on that folder? It should give an error, but the error it gives will be useful information.

**Comment by H-A-M-G-E-R** [comment]
the files are created in C:\GitHub\decomp-permuter-agbcc\nonmatchings\BoxFallingDebrisFalling, and I run the command in C:\GitHub\decomp-permuter-agbcc

**Comment by WhenGryphonsFly** [comment]
(My best attempt at explaining `--keep` is this: normally if the import script encounters an error, the files should not be created, as the permuter will not work on those files and will normally give nonsense errors. However, given how late in the import process the error is occurring, the error that the permute script will produce will likely be related to the error the import script is encountering. As such, it is useful to add the `--keep` flag to force the import script to keep the files even if it encounters an error.)

To answer the question that you asked while I was typing the above explanation, yes, run `./permute.py ./nonmatchings/BoxFallingDebrisFalling` from `C:\GitHub\decomp-permuter-agbcc` in MSYS2

**Comment by H-A-M-G-E-R** [comment]
```
"/c/Users/H A M/AppData/Local/Programs/Python/Python312/python.exe" ./permuter.py ./nonmatchings/BoxFallingDebrisFalling
Loading...
./nonmatchings/BoxFallingDebrisFalling\compile.sh must be marked executable.

```

**Comment by WhenGryphonsFly** [comment]
Okay, I dug up an old Windows laptop of mine, so I know how to see if a file is executable. Go into the nonmatchings folder, find compile.sh, right click it, click Properties, go to the Security tab, and screenshot the window with Win+Shift+S.

At this point, at least half of this issue needs to be handled by upstream. I'd like to keep working on this here until I know how much (if any) is due to the changes I've made. Once that's done, I can work with upstream to resolve the issues.

**Comment by H-A-M-G-E-R** [comment]
I did just that and saw that everyone can execute compile.sh

**Comment by WhenGryphonsFly** [comment]
One last shot, can you get an MSYS2 terminal open in the folder with compile.sh, and then run `ls -l` and give me the output? It could be that it's unexecutable in MSYS2 for whatever reason

**Comment by H-A-M-G-E-R** [comment]
-rwxr-xr-x

**Comment by H-A-M-G-E-R** [comment]
i can execute compile.sh directly but not through permuter.py

**Comment by WhenGryphonsFly** [comment]
Does compile.sh itself produce any errors when you run it in a terminal?

**Comment by H-A-M-G-E-R** [comment]
different errors
```
$ ./compile.sh
realpath: '': No such file or directory
realpath: '': No such file or directory
agbcc: No such file or directory
Assembler messages:
Fatal error: can't create : Invalid argument
```
the compile.sh is
```
#!/usr/bin/env bash
INPUT="$(realpath "$1")"
OUTPUT="$(realpath "$3")"
cd 'C:\Github\mf'
/c/GitHub/agbcc/agbcc.exe -O2 -mthumb-interwork -fhex-asm -o /dev/stdout "$INPUT" | /c/devkitPro/devkitARM/bin/arm-none-eabi-as.exe -mcpu=arm7tdmi -o "$OUTPUT"
```

**Comment by WhenGryphonsFly** [comment]
Oh, yeah, it needs arguments. One second, let me see what arguments it needs

**Comment by WhenGryphonsFly** [comment]
Run `./compile.sh base.c -o base.o`

**Comment by H-A-M-G-E-R** [comment]
that's unrelated to the `./nonmatchings/BoxFallingDebrisFalling\compile.sh must be marked executable.` error

**Comment by WhenGryphonsFly** [comment]
Yes, but at this point I'm fairly confident there are multiple issues. Any errors that `./compile.sh base.c -o base.o` generates should shed light on the import script error, which I believe to be unrelated to the `./nonmatchings/BoxFallingDebrisFalling\compile.sh must be marked executable.` error

**Comment by H-A-M-G-E-R** [comment]
I changed compile.sh to
```
#!/usr/bin/env bash
INPUT="$(realpath "$1")"
OUTPUT="$(realpath "$3")"
../../../agbcc/agbcc.exe -O2 -mthumb-interwork -fhex-asm -o /dev/stdout "$INPUT" | ../../../../devkitPro/devkitARM/bin/arm-none-eabi-as.exe -mcpu=arm7tdmi -o "$OUTPUT"
```
putted them in `C:\GitHub\mf\nonmatchings\BoxFallingDebrisFalling`, and ran ./compile.sh base.c -o base.o without errors

**Comment by WhenGryphonsFly** [comment]
Even if that's not what I asked you to do, that is useful information. Can you edit your permuter_settings.toml to be the following:
```
compiler_type = "gcc"
compiler_command = "../agbcc/agbcc.exe -O2 -mthumb-interwork -fhex-asm -o /dev/stdout | ../../devkitPro/devkitARM/bin/arm-none-eabi-as.exe -mcpu=arm7tdmi"
assembler_command = "../../devkitPro/devkitARM/bin/arm-none-eabi-as.exe -mcpu=arm7tdmi"
```

Then delete nonmatchings, and run the import script from the decomp-permuter-agbcc directory in MSYS2. Unless the result is very weird, this will hopefully be the second-to-last command I ask you to run.

**Comment by H-A-M-G-E-R** [comment]
STILL
```
$ "/c/Users/H A M/AppData/Local/Programs/Python/Python312/python.exe" ./import.py ../mf/expected_objs/BoxFallingDebrisFalling.c ../mf/expected_objs/BoxFallingDebrisFalling.o BoxFallingDebrisFalling   Compiler type: gcc
Function name: BoxFallingDebrisFalling
Compiler: ../agbcc/agbcc.exe -O2 -mthumb-interwork -fhex-asm -o /dev/stdout '|' ../../devkitPro/devkitARM/bin/arm-none-eabi-as.exe -mcpu=arm7tdmi {input} -o {output}
Assembler: ../../devkitPro/devkitARM/bin/arm-none-eabi-as.exe -mcpu=arm7tdmi {input} -o {output}
Preserving no macros. Use --preserve-macros='<regex>' to override.

Deleting directory nonmatchings/BoxFallingDebrisFalling (run with --keep to preserve it).
Traceback (most recent call last):
  File "C:\Github\decomp-permuter-agbcc\import.py", line 927, in <module>
    main(sys.argv[1:])
  File "C:\Github\decomp-permuter-agbcc\import.py", line 916, in main
    compile_base(compile_script, compilable_source, base_c_file, base_o_file)
  File "C:\Github\decomp-permuter-agbcc\import.py", line 757, in compile_base
    o_file = compiler.compile(source)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Github\decomp-permuter-agbcc\src\compiler.py", line 43, in compile
    subprocess.check_call(
  File "C:\Users\H A M\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H A M\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H A M\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\H A M\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application

```

**Comment by WhenGryphonsFly** [comment]
Okay, last two commands then. First, run the import script with `--keep`. Second, run `./compile.sh base.c -o base.o ` without modifying compile.sh. (Both in MSYS2.) Please provide both the contents of compile.sh as well as the output of the compile.sh command. The import script with keep should produce errors, these errors can be ignored.

**Comment by H-A-M-G-E-R** [comment]
[BoxFallingDebrisFalling.zip](https://github.com/user-attachments/files/17427357/BoxFallingDebrisFalling.zip)

**Comment by WhenGryphonsFly** [comment]
Just checking, no errors on compile.sh?

**Comment by H-A-M-G-E-R** [comment]
no errors, didn't produce a single message

**Comment by WhenGryphonsFly** [comment]
Okay, that's fine. Here are the the two issues I've identified:

- Something is wrong with the import script, and I have no idea what. Given the lines reported, I strongly suspect it's an upstream issue. I did not modify those lines, nor did I modify any lines that I would reasonably believe could cause it to fail with that message. (If the import script was complaining about bad arguments, then I would suspect it to be my changes, but it's complaining about the executable.)
- The permute script has an issue where it cannot determine that a file is executable. I suspect this is an interaction between the permute script, Windows, and MSYS2. The mismatched path separators in `./nonmatchings/BoxFallingDebrisFalling\compile.sh must be marked executable.` is something to investigate. This is definitively an upstream issue; I did not touch `permute.py` or any of its dependencies.

I will report these issues to upstream. For now, I don't know what more can be done. If the second issue can be resolved then you would be able to use the `--keep` flag to bypass the first issue, but it may be a while before the second issue is fixed.

**Comment by H-A-M-G-E-R** [comment]
When I try to do it with upstream, it gives a different error
```
./import.py ../mf/expected_objs/BoxFallingDebrisFalling.c ../mf/expected_objs/BoxFallingDebrisFalling.o BoxFallingDebrisFalling
Compiler type: gcc
Traceback (most recent call last):
  File "C:\GitHub\decomp-permuter\import.py", line 964, in <module>
    main(sys.argv[1:])
  File "C:\GitHub\decomp-permuter\import.py", line 880, in main
    func_name, asm_cont = parse_asm(root_dir, args.c_file, args.asm_file_or_func_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\decomp-permuter\import.py", line 178, in parse_asm
    asm_cont = f.read()
               ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 52-53: invalid continuation byte
```

**Comment by H-A-M-G-E-R** [comment]
now i matched it without the permuter
https://github.com/H-A-M-G-E-R/mf/commit/f198b5db0596c8ee3b27b824e51940f3c84b1fff#diff-a5fc308d2e8fa6c1ed0484de25a827513046a85bb615d712e68db2f3295abbc1

**Comment by WhenGryphonsFly** [comment]
> When I try to do it with upstream, it gives a different error

This error is related to the fact that decomp-permuter-agbcc expects a .o file for the target, whereas decomp-permuter expects a .s file for the target. This change was made because other tools expect .o files for the target, namely objdiff.

> now i matched it without the permuter

Glad to hear it! I'll keep this open until upstream resolves the issue.

**Comment by H-A-M-G-E-R** [comment]
EDIT: used WSL, gave a different error
```
/mnt/c/GitHub/mf# python3 ../decomp-permuter-agbcc/import.py expected_objs/CoreXShell.c expected_objs/CoreXShell.o CoreXShell
Compiler type: gcc
Function name: CoreXShell
Compiler: /mnt/c/Github/agbcc/agbcc.exe -O2 -mthumb-interwork -fhex-asm -o /dev/stdout '|' /mnt/c/devkitPro/devkitARM/bin/arm-none-eabi-as.exe -mcpu=arm7tdmi {input} -o {output}
Assembler: /mnt/c/devkitPro/devkitARM/bin/arm-none-eabi-as.exe -mcpu=arm7tdmi {input} -o {output}
Preserving no macros. Use --preserve-macros='<regex>' to override.
Assembler messages:
Fatal error: can't create /tmp/permuter5c77nohw.o: No such file or directory
agbcc: /tmp/permuterpakvekzp.c: No such file or directory
Warning: failed to compile .c file.

Done. Imported into nonmatchings/CoreXShell
```
Here's now what permuter_settings.toml looks like:
```
compiler_type = "gcc"
compiler_command = "/mnt/c/Github/agbcc/agbcc.exe -O2 -mthumb-interwork -fhex-asm -o /dev/stdout | /mnt/c/devkitPro/devkitARM/bin/arm-none-eabi-as.exe -mcpu=arm7tdmi"
assembler_command = "/mnt/c/devkitPro/devkitARM/bin/arm-none-eabi-as.exe -mcpu=arm7tdmi"
```
